/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	"time"

	v1 "github.com/Percona-Lab/pxc-service-broker/pkg/apis/pxc/v1"
	scheme "github.com/Percona-Lab/pxc-service-broker/pkg/client/clientset/versioned/scheme"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// PerconaXtraDBClusterRestoresGetter has a method to return a PerconaXtraDBClusterRestoreInterface.
// A group's client should implement this interface.
type PerconaXtraDBClusterRestoresGetter interface {
	PerconaXtraDBClusterRestores(namespace string) PerconaXtraDBClusterRestoreInterface
}

// PerconaXtraDBClusterRestoreInterface has methods to work with PerconaXtraDBClusterRestore resources.
type PerconaXtraDBClusterRestoreInterface interface {
	Create(*v1.PerconaXtraDBClusterRestore) (*v1.PerconaXtraDBClusterRestore, error)
	Update(*v1.PerconaXtraDBClusterRestore) (*v1.PerconaXtraDBClusterRestore, error)
	Delete(name string, options *metav1.DeleteOptions) error
	DeleteCollection(options *metav1.DeleteOptions, listOptions metav1.ListOptions) error
	Get(name string, options metav1.GetOptions) (*v1.PerconaXtraDBClusterRestore, error)
	List(opts metav1.ListOptions) (*v1.PerconaXtraDBClusterRestoreList, error)
	Watch(opts metav1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1.PerconaXtraDBClusterRestore, err error)
	PerconaXtraDBClusterRestoreExpansion
}

// perconaXtraDBClusterRestores implements PerconaXtraDBClusterRestoreInterface
type perconaXtraDBClusterRestores struct {
	client rest.Interface
	ns     string
}

// newPerconaXtraDBClusterRestores returns a PerconaXtraDBClusterRestores
func newPerconaXtraDBClusterRestores(c *PxcV1Client, namespace string) *perconaXtraDBClusterRestores {
	return &perconaXtraDBClusterRestores{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the perconaXtraDBClusterRestore, and returns the corresponding perconaXtraDBClusterRestore object, and an error if there is any.
func (c *perconaXtraDBClusterRestores) Get(name string, options metav1.GetOptions) (result *v1.PerconaXtraDBClusterRestore, err error) {
	result = &v1.PerconaXtraDBClusterRestore{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("perconaxtradbclusterrestores").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of PerconaXtraDBClusterRestores that match those selectors.
func (c *perconaXtraDBClusterRestores) List(opts metav1.ListOptions) (result *v1.PerconaXtraDBClusterRestoreList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1.PerconaXtraDBClusterRestoreList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("perconaxtradbclusterrestores").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested perconaXtraDBClusterRestores.
func (c *perconaXtraDBClusterRestores) Watch(opts metav1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("perconaxtradbclusterrestores").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch()
}

// Create takes the representation of a perconaXtraDBClusterRestore and creates it.  Returns the server's representation of the perconaXtraDBClusterRestore, and an error, if there is any.
func (c *perconaXtraDBClusterRestores) Create(perconaXtraDBClusterRestore *v1.PerconaXtraDBClusterRestore) (result *v1.PerconaXtraDBClusterRestore, err error) {
	result = &v1.PerconaXtraDBClusterRestore{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("perconaxtradbclusterrestores").
		Body(perconaXtraDBClusterRestore).
		Do().
		Into(result)
	return
}

// Update takes the representation of a perconaXtraDBClusterRestore and updates it. Returns the server's representation of the perconaXtraDBClusterRestore, and an error, if there is any.
func (c *perconaXtraDBClusterRestores) Update(perconaXtraDBClusterRestore *v1.PerconaXtraDBClusterRestore) (result *v1.PerconaXtraDBClusterRestore, err error) {
	result = &v1.PerconaXtraDBClusterRestore{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("perconaxtradbclusterrestores").
		Name(perconaXtraDBClusterRestore.Name).
		Body(perconaXtraDBClusterRestore).
		Do().
		Into(result)
	return
}

// Delete takes name of the perconaXtraDBClusterRestore and deletes it. Returns an error if one occurs.
func (c *perconaXtraDBClusterRestores) Delete(name string, options *metav1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("perconaxtradbclusterrestores").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *perconaXtraDBClusterRestores) DeleteCollection(options *metav1.DeleteOptions, listOptions metav1.ListOptions) error {
	var timeout time.Duration
	if listOptions.TimeoutSeconds != nil {
		timeout = time.Duration(*listOptions.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("perconaxtradbclusterrestores").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Timeout(timeout).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched perconaXtraDBClusterRestore.
func (c *perconaXtraDBClusterRestores) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1.PerconaXtraDBClusterRestore, err error) {
	result = &v1.PerconaXtraDBClusterRestore{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("perconaxtradbclusterrestores").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
