/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1

import (
	time "time"

	pxcv1 "github.com/Percona-Lab/pxc-service-broker/pkg/apis/pxc/v1"
	versioned "github.com/Percona-Lab/pxc-service-broker/pkg/client/clientset/versioned"
	internalinterfaces "github.com/Percona-Lab/pxc-service-broker/pkg/client/informers/externalversions/internalinterfaces"
	v1 "github.com/Percona-Lab/pxc-service-broker/pkg/client/listers/pxc/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// PerconaXtraDBClusterBackupInformer provides access to a shared informer and lister for
// PerconaXtraDBClusterBackups.
type PerconaXtraDBClusterBackupInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1.PerconaXtraDBClusterBackupLister
}

type perconaXtraDBClusterBackupInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewPerconaXtraDBClusterBackupInformer constructs a new informer for PerconaXtraDBClusterBackup type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewPerconaXtraDBClusterBackupInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredPerconaXtraDBClusterBackupInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredPerconaXtraDBClusterBackupInformer constructs a new informer for PerconaXtraDBClusterBackup type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredPerconaXtraDBClusterBackupInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options metav1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.PxcV1().PerconaXtraDBClusterBackups(namespace).List(options)
			},
			WatchFunc: func(options metav1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.PxcV1().PerconaXtraDBClusterBackups(namespace).Watch(options)
			},
		},
		&pxcv1.PerconaXtraDBClusterBackup{},
		resyncPeriod,
		indexers,
	)
}

func (f *perconaXtraDBClusterBackupInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredPerconaXtraDBClusterBackupInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *perconaXtraDBClusterBackupInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&pxcv1.PerconaXtraDBClusterBackup{}, f.defaultInformer)
}

func (f *perconaXtraDBClusterBackupInformer) Lister() v1.PerconaXtraDBClusterBackupLister {
	return v1.NewPerconaXtraDBClusterBackupLister(f.Informer().GetIndexer())
}
