/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	pxcv1 "github.com/Percona-Lab/pxc-service-broker/pkg/apis/pxc/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakePerconaXtraDBClusterRestores implements PerconaXtraDBClusterRestoreInterface
type FakePerconaXtraDBClusterRestores struct {
	Fake *FakePxcV1
	ns   string
}

var perconaxtradbclusterrestoresResource = schema.GroupVersionResource{Group: "pxc.percona.com", Version: "v1", Resource: "perconaxtradbclusterrestores"}

var perconaxtradbclusterrestoresKind = schema.GroupVersionKind{Group: "pxc.percona.com", Version: "v1", Kind: "PerconaXtraDBClusterRestore"}

// Get takes name of the perconaXtraDBClusterRestore, and returns the corresponding perconaXtraDBClusterRestore object, and an error if there is any.
func (c *FakePerconaXtraDBClusterRestores) Get(name string, options v1.GetOptions) (result *pxcv1.PerconaXtraDBClusterRestore, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(perconaxtradbclusterrestoresResource, c.ns, name), &pxcv1.PerconaXtraDBClusterRestore{})

	if obj == nil {
		return nil, err
	}
	return obj.(*pxcv1.PerconaXtraDBClusterRestore), err
}

// List takes label and field selectors, and returns the list of PerconaXtraDBClusterRestores that match those selectors.
func (c *FakePerconaXtraDBClusterRestores) List(opts v1.ListOptions) (result *pxcv1.PerconaXtraDBClusterRestoreList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(perconaxtradbclusterrestoresResource, perconaxtradbclusterrestoresKind, c.ns, opts), &pxcv1.PerconaXtraDBClusterRestoreList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &pxcv1.PerconaXtraDBClusterRestoreList{ListMeta: obj.(*pxcv1.PerconaXtraDBClusterRestoreList).ListMeta}
	for _, item := range obj.(*pxcv1.PerconaXtraDBClusterRestoreList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested perconaXtraDBClusterRestores.
func (c *FakePerconaXtraDBClusterRestores) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(perconaxtradbclusterrestoresResource, c.ns, opts))

}

// Create takes the representation of a perconaXtraDBClusterRestore and creates it.  Returns the server's representation of the perconaXtraDBClusterRestore, and an error, if there is any.
func (c *FakePerconaXtraDBClusterRestores) Create(perconaXtraDBClusterRestore *pxcv1.PerconaXtraDBClusterRestore) (result *pxcv1.PerconaXtraDBClusterRestore, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(perconaxtradbclusterrestoresResource, c.ns, perconaXtraDBClusterRestore), &pxcv1.PerconaXtraDBClusterRestore{})

	if obj == nil {
		return nil, err
	}
	return obj.(*pxcv1.PerconaXtraDBClusterRestore), err
}

// Update takes the representation of a perconaXtraDBClusterRestore and updates it. Returns the server's representation of the perconaXtraDBClusterRestore, and an error, if there is any.
func (c *FakePerconaXtraDBClusterRestores) Update(perconaXtraDBClusterRestore *pxcv1.PerconaXtraDBClusterRestore) (result *pxcv1.PerconaXtraDBClusterRestore, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(perconaxtradbclusterrestoresResource, c.ns, perconaXtraDBClusterRestore), &pxcv1.PerconaXtraDBClusterRestore{})

	if obj == nil {
		return nil, err
	}
	return obj.(*pxcv1.PerconaXtraDBClusterRestore), err
}

// Delete takes name of the perconaXtraDBClusterRestore and deletes it. Returns an error if one occurs.
func (c *FakePerconaXtraDBClusterRestores) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(perconaxtradbclusterrestoresResource, c.ns, name), &pxcv1.PerconaXtraDBClusterRestore{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakePerconaXtraDBClusterRestores) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(perconaxtradbclusterrestoresResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &pxcv1.PerconaXtraDBClusterRestoreList{})
	return err
}

// Patch applies the patch and returns the patched perconaXtraDBClusterRestore.
func (c *FakePerconaXtraDBClusterRestores) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *pxcv1.PerconaXtraDBClusterRestore, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(perconaxtradbclusterrestoresResource, c.ns, name, pt, data, subresources...), &pxcv1.PerconaXtraDBClusterRestore{})

	if obj == nil {
		return nil, err
	}
	return obj.(*pxcv1.PerconaXtraDBClusterRestore), err
}
