/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	pxcv1 "github.com/Percona-Lab/pxc-service-broker/pkg/apis/pxc/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakePerconaXtraDBClusters implements PerconaXtraDBClusterInterface
type FakePerconaXtraDBClusters struct {
	Fake *FakePxcV1
	ns   string
}

var perconaxtradbclustersResource = schema.GroupVersionResource{Group: "pxc.percona.com", Version: "v1", Resource: "perconaxtradbclusters"}

var perconaxtradbclustersKind = schema.GroupVersionKind{Group: "pxc.percona.com", Version: "v1", Kind: "PerconaXtraDBCluster"}

// Get takes name of the perconaXtraDBCluster, and returns the corresponding perconaXtraDBCluster object, and an error if there is any.
func (c *FakePerconaXtraDBClusters) Get(name string, options v1.GetOptions) (result *pxcv1.PerconaXtraDBCluster, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(perconaxtradbclustersResource, c.ns, name), &pxcv1.PerconaXtraDBCluster{})

	if obj == nil {
		return nil, err
	}
	return obj.(*pxcv1.PerconaXtraDBCluster), err
}

// List takes label and field selectors, and returns the list of PerconaXtraDBClusters that match those selectors.
func (c *FakePerconaXtraDBClusters) List(opts v1.ListOptions) (result *pxcv1.PerconaXtraDBClusterList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(perconaxtradbclustersResource, perconaxtradbclustersKind, c.ns, opts), &pxcv1.PerconaXtraDBClusterList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &pxcv1.PerconaXtraDBClusterList{ListMeta: obj.(*pxcv1.PerconaXtraDBClusterList).ListMeta}
	for _, item := range obj.(*pxcv1.PerconaXtraDBClusterList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested perconaXtraDBClusters.
func (c *FakePerconaXtraDBClusters) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(perconaxtradbclustersResource, c.ns, opts))

}

// Create takes the representation of a perconaXtraDBCluster and creates it.  Returns the server's representation of the perconaXtraDBCluster, and an error, if there is any.
func (c *FakePerconaXtraDBClusters) Create(perconaXtraDBCluster *pxcv1.PerconaXtraDBCluster) (result *pxcv1.PerconaXtraDBCluster, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(perconaxtradbclustersResource, c.ns, perconaXtraDBCluster), &pxcv1.PerconaXtraDBCluster{})

	if obj == nil {
		return nil, err
	}
	return obj.(*pxcv1.PerconaXtraDBCluster), err
}

// Update takes the representation of a perconaXtraDBCluster and updates it. Returns the server's representation of the perconaXtraDBCluster, and an error, if there is any.
func (c *FakePerconaXtraDBClusters) Update(perconaXtraDBCluster *pxcv1.PerconaXtraDBCluster) (result *pxcv1.PerconaXtraDBCluster, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(perconaxtradbclustersResource, c.ns, perconaXtraDBCluster), &pxcv1.PerconaXtraDBCluster{})

	if obj == nil {
		return nil, err
	}
	return obj.(*pxcv1.PerconaXtraDBCluster), err
}

// Delete takes name of the perconaXtraDBCluster and deletes it. Returns an error if one occurs.
func (c *FakePerconaXtraDBClusters) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(perconaxtradbclustersResource, c.ns, name), &pxcv1.PerconaXtraDBCluster{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakePerconaXtraDBClusters) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(perconaxtradbclustersResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &pxcv1.PerconaXtraDBClusterList{})
	return err
}

// Patch applies the patch and returns the patched perconaXtraDBCluster.
func (c *FakePerconaXtraDBClusters) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *pxcv1.PerconaXtraDBCluster, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(perconaxtradbclustersResource, c.ns, name, pt, data, subresources...), &pxcv1.PerconaXtraDBCluster{})

	if obj == nil {
		return nil, err
	}
	return obj.(*pxcv1.PerconaXtraDBCluster), err
}
